development:
    dialect: sqlite3
    datasource: migrator-test.db
    dir: migrations/sqlite3

production:
    dialect: postgres
    datasource: host=localhost port=5432 user=postgres password=vagrant dbname=test-dipta
    dir: migrations/postgres