// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/proto_example.proto

/*
Package proto_example is a generated protocol buffer package.

It is generated from these files:
	proto/proto_example.proto

It has these top-level messages:
	MyRequest
	MyReply
*/
package proto_example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MyRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *MyRequest) Reset()                    { *m = MyRequest{} }
func (m *MyRequest) String() string            { return proto.CompactTextString(m) }
func (*MyRequest) ProtoMessage()               {}
func (*MyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MyReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *MyReply) Reset()                    { *m = MyReply{} }
func (m *MyReply) String() string            { return proto.CompactTextString(m) }
func (*MyReply) ProtoMessage()               {}
func (*MyReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MyReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*MyRequest)(nil), "proto_example.MyRequest")
	proto.RegisterType((*MyReply)(nil), "proto_example.MyReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MyService service

type MyServiceClient interface {
	SayHello(ctx context.Context, in *MyRequest, opts ...grpc.CallOption) (*MyReply, error)
}

type myServiceClient struct {
	cc *grpc.ClientConn
}

func NewMyServiceClient(cc *grpc.ClientConn) MyServiceClient {
	return &myServiceClient{cc}
}

func (c *myServiceClient) SayHello(ctx context.Context, in *MyRequest, opts ...grpc.CallOption) (*MyReply, error) {
	out := new(MyReply)
	err := grpc.Invoke(ctx, "/proto_example.MyService/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MyService service

type MyServiceServer interface {
	SayHello(context.Context, *MyRequest) (*MyReply, error)
}

func RegisterMyServiceServer(s *grpc.Server, srv MyServiceServer) {
	s.RegisterService(&_MyService_serviceDesc, srv)
}

func _MyService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_example.MyService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).SayHello(ctx, req.(*MyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto_example.MyService",
	HandlerType: (*MyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _MyService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto_example.proto",
}

func init() { proto.RegisterFile("proto/proto_example.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x07, 0x93, 0xf1, 0xa9, 0x15, 0x89, 0xb9, 0x05, 0x39, 0xa9, 0x7a, 0x60, 0x9e, 0x10,
	0x2f, 0x8a, 0xa0, 0x94, 0x4c, 0x7a, 0x7e, 0x7e, 0x7a, 0x4e, 0xaa, 0x7e, 0x62, 0x41, 0xa6, 0x7e,
	0x62, 0x5e, 0x5e, 0x7e, 0x49, 0x62, 0x49, 0x66, 0x7e, 0x5e, 0x31, 0x44, 0xb1, 0x92, 0x3c, 0x17,
	0xa7, 0x6f, 0x65, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62,
	0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0xad, 0xa4, 0xcc, 0xc5, 0x0e, 0x52,
	0x50, 0x90, 0x53, 0x29, 0x24, 0xc1, 0xc5, 0x9e, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x0e, 0x53, 0x01,
	0xe3, 0x1a, 0x45, 0x83, 0x4c, 0x09, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0xf2, 0xe3, 0xe2,
	0x08, 0x4e, 0xac, 0xf4, 0x48, 0xcd, 0xc9, 0xc9, 0x17, 0x92, 0xd0, 0x43, 0x75, 0x21, 0xdc, 0x2e,
	0x29, 0x31, 0x2c, 0x32, 0x05, 0x39, 0x95, 0x4a, 0x02, 0x4d, 0x97, 0x9f, 0x4c, 0x66, 0xe2, 0x52,
	0x62, 0xd5, 0x4f, 0x4d, 0xce, 0xc8, 0xb7, 0x62, 0xd4, 0x4a, 0x62, 0x03, 0x2b, 0x34, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x22, 0xbd, 0x6c, 0xbb, 0xf3, 0x00, 0x00, 0x00,
}
